### ISSUE TITLE
You Forgot To Add Footer In Store Page

### ISSUE THREAD

**Issue by BossGamerz09** [HolaClient/X#1]
![image](https://user-images.githubusercontent.com/119093806/233842757-b66feb84-8885-45f5-be3d-d84fbfe3d3f4.png)
![image](https://user-images.githubusercontent.com/119093806/233842773-084aca86-5004-4066-bfe1-3c90853a4623.png)
Btw My Discord Tag is Mʀ_Dᴇᴠɪʟ | Version 1.2

**Comment by recabasic** [comment]
Hey BossGamerz09,
Thanks for reaching us, As your problem quotes that I have not included footer in store page. It is because of the mobile support the footer was going crazy but no worries for now because in 1.3 we included the footer in the right position and it is still mobile optimized. We didn't include footer in v1.2 as our wish. Thank you for pointing out this issue we'd love more bug reports from you.
